[world]
name = "Provable Games"
description = "Slot world for testing PG games and infrastructure"
seed = "pg"

[namespace]
default = "darkshuffle"

[writers]
"darkshuffle" = [
    "darkshuffle-game_systems",
    "darkshuffle-battle_systems",
    "darkshuffle-season_systems",
    "darkshuffle-draft_systems",
    "darkshuffle-map_systems",
    "darkshuffle-config_systems",
]

[env]
chain_id = "WP_PG"
rpc_url = "https://api.cartridge.gg/x/pg/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
world_address = "0x04254b770ec69289dae26a6b488cc75689b3765171423cae8d648323ae4de44a"

