[world]
name = "Provable Games"
description = "PG Slot World"
seed = "pg"

[world.socials]
x = "https://x.com/await_0x"
github = "https://github.com/Await-0x/dark-shuffle"

[init_call_args]
"ds-game_systems" = [
    "0x03c0f67740e3fe298a52fe75dd24b4981217406f133e0835331379731b67dc92",
]

[namespace]
default = "ds"

[writers]
"ds" = [
    "ds-game_systems",
    "ds-battle_systems",
    "ds-draft_systems",
    "ds-map_systems",
    "ds-config_systems",
]

[env]
chain_id = "WP_PG"
rpc_url = "https://api.cartridge.gg/x/pg/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
world_address = "0x04254b770ec69289dae26a6b488cc75689b3765171423cae8d648323ae4de44a"
