[world]
name = "Realms World"
website = "https://realms.world/"
description = "DNC"
seed = "DNC"

[env]
chain_id = "SN_MAINNET"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x06a9e4c6f0799160ea8ddc43ff982a5f83d7f633e9732ce42701de1288ff705f"
world_block = 948010

[namespace]
default = "ds_v1_1_2"

[writers]
"ds_v1_1_2" = [
    "ds_v1_1_2-game_systems",
    "ds_v1_1_2-battle_systems",
    "ds_v1_1_2-draft_systems",
    "ds_v1_1_2-map_systems",
    "ds_v1_1_2-config_systems",
]

[init_call_args]
"ds_v1_1_2-game_systems" = [
    "0x000B39b235b44c53a2E9F0c5D35939D9C8E8dAFDd0a2ba2E695b501Fc1e9fd2f",
]