[package]
cairo-version = "=2.8.4"
name = "darkshuffle"
version = "1.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.8.4"
cartridge_vrf = { git = "https://github.com/loothero/vrf.git", branch = "feat/upgrade-starknet-2.8.5" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v1.0.9" }
tournaments= { git = "https://github.com/Provable-Games/tournaments.git", branch = "feat/dark-shuffle-integration"}
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.18.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.18.0" }
[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.9" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
    "tournaments::components::models::game::m_GameMetadata",
    "tournaments::components::models::game::m_TokenMetadata",
    "tournaments::components::models::game::m_GameCounter",
    "tournaments::components::models::game::m_Score",
    "tournaments::components::models::game::m_Settings",
    "tournaments::components::models::game::m_SettingsDetails",
    "tournaments::components::models::game::m_SettingsCounter",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]