[package]
cairo-version = "=2.10.1"
edition = "2023_01"
name = "darkshuffle"
version = "1.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.10.1"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
achievement = { git = "https://github.com/cartridge-gg/arcade", rev = "1353aab3dec66c2de7aad7f37f91b4002d86b2b8" }
game_components_minigame = { git = "https://github.com/Provable-Games/game-components", tag = "v1.5.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }
denshokan = { git = "https://github.com/Provable-Games/denshokan", tag = "v1.5.0" }
game_components_denshokan = { git = "https://github.com/Provable-Games/game-components", tag = "v1.5.0" }
game_components_metagame = { git = "https://github.com/Provable-Games/game-components", tag = "v1.5.0" }
game_components_utils = { git = "https://github.com/Provable-Games/game-components", tag = "v1.5.0" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.5.0" }
cairo_test = "2.10.1"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
        "game_components_minigame::tests::models::minigame::m_ScoreObjective",
    "game_components_minigame::tests::models::minigame::m_ScoreObjectiveCount",
    "game_components_minigame::tests::models::minigame::m_Settings",
    "game_components_minigame::tests::models::minigame::m_SettingsDetails",
    "game_components_minigame::tests::models::minigame::m_SettingsCounter",
    "game_components_minigame::tests::models::minigame::m_Score",
    "game_components_metagame::tests::models::metagame::m_Context",
    "game_components_minigame::tests::mocks::minigame_mock::minigame_mock",
    "game_components_metagame::tests::mocks::metagame_mock::metagame_mock",
    "denshokan::models::denshokan::m_GameMetadata",
    "denshokan::models::denshokan::m_GameRegistry",
    "denshokan::models::denshokan::m_GameRegistryId",
    "denshokan::models::denshokan::m_GameCounter",
    "denshokan::models::denshokan::m_MinterRegistry",
    "denshokan::models::denshokan::m_MinterRegistryId",
    "denshokan::models::denshokan::m_MinterCounter",
    "denshokan::models::denshokan::m_TokenMetadata",
    "denshokan::models::denshokan::m_TokenCounter",
    "denshokan::models::denshokan::m_TokenPlayerName",
    "denshokan::models::denshokan::m_TokenObjective",
    "denshokan::denshokan::denshokan::e_Owners",
    "denshokan::denshokan::denshokan::e_ScoreUpdate",
    "denshokan::denshokan::denshokan::e_ObjectiveData",
    "denshokan::denshokan::denshokan::e_SettingsData",
    "denshokan::denshokan::denshokan::e_TokenContextData",
    "denshokan::denshokan::denshokan",
]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[profile.sepolia]
[profile.slot]
[profile.mainnet]