[indexing]
contracts = [
    "erc721:0x25dd1faa4f94d1ddd523d7db4697c10a34a09d7b55b4758995a070fd9d61498"
]

namespaces = ["ds_v1_2_0", "budokan_v_1_0_4"]

[events]
raw = true
historical = ["ds_v1_2_0-TrophyCreation", "ds_v1_2_0-TrophyProgression"]
