[indexing]
contracts = [
    "erc721:0x78cceb0902cab94a6c783b23168a45bc4dfa4f1ee35e7edaf936146d458dbd0"
]

[events]
raw = true
historical = ["ds_v1_2_0-TrophyCreation", "ds_v1_2_0-TrophyProgression"]
