[indexing]
contracts = [
    "erc721:0x3a8380c0b59277df5b268cd6b7ab88883d6d6c79d34018a58a71b186558392"
]

namespaces = ["ds_v1_2_0", "budokan_v_1_0_4"]

[events]
raw = true
historical = ["ds_v1_2_0-TrophyCreation", "ds_v1_2_0-TrophyProgression"]
