[indexing]
contracts = [
    "erc721:0x49c0db18f11bfd05dcb57f2c4eec0a1f95f109f7861026bd960dfee360aecae"
]

[events]
raw = true
historical = ["ds_v1_2_0-TrophyCreation", "ds_v1_2_0-TrophyProgression"]
