[indexing]
contracts = [
    "erc721:0x5af07053c097793e43c4dffbc26990c5d8b08ee59381163037720dff1f8aa60"
]

namespaces = ["ds_v1_2_0", "budokan_v_1_0_4"]

[events]
raw = true
historical = ["ds_v1_2_0-TrophyCreation", "ds_v1_2_0-TrophyProgression"]
